global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'polyverse-hub'
    static_configs:
      - targets: ['hub:8000']
  
  - job_name: 'rust-signal'
    static_configs:
      - targets: ['rust_signal:8080']
  
  - job_name: 'go-orchestrator'
    static_configs:
      - targets: ['go_orchestrator:8081']
  
  - job_name: 'java-recommender'
    static_configs:
      - targets: ['java_recommender:8082']

